name: k6 Performance Test

on:
  workflow_dispatch:
    inputs:
      tps:
        description: 'Transactions per second (TPS) for the load test'
        required: true
        default: '2'
  push:
    branches: main 
    
jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies for building k6
        run: |
          sudo apt update
          sudo apt install -y git make gcc

      - name: Install xk6 and build k6 with influxdb extension
        run: |
          go install go.k6.io/xk6/cmd/xk6@latest
          ~/go/bin/xk6 build --with github.com/grafana/xk6-output-influxdb@latest

      - name: Run k6 Load Test and push to InfluxDB
        env:
          INFLUXDB_URL: https://us-east-1-1.aws.cloud2.influxdata.com
          INFLUXDB_ORG: k6demo
          INFLUXDB_BUCKET: k6testbucket
          INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
        run: |
          ./k6 run --out xk6-influxdb=$INFLUXDB_URL?org=$INFLUXDB_ORG\&bucket=$INFLUXDB_BUCKET\&token=$INFLUXDB_TOKEN --env TPS=${{ github.event.inputs.tps }} test.js